version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    container_name: quattrotech-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=quattrotech
    volumes:
      - quattrotech-data:/data/db

volumes:
  quattrotech-data:
